theme: jekyll-theme-cayman
title: Trade Study Execution and Analysis
author: Stephen Zq
description: Designed a website to conduct and store trade studies using Vue.js, HTML, CSS, and JavaScript. Created algorithms with Analytical Hierarchy Process and analyzed subsequently data to identify trends using Java and MATLAB.
